export class PageDb {
    public static all = [
        {
            "id": 228990,
            "deleteStatus": "Normal",
            "seoTitle": "网站模板",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "首页",
            "seoKeyword": "",
            "domain": "?userId=228990",
            "pv": 0,
            "pageType": "normal",
            "sortId": 0,
            "renderId": "",
            "associateId": "",
            "viewWidth": 1200,
            "synchro": false
        },
        {
            "id": 228991,
            "deleteStatus": "Normal",
            "seoTitle": "",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "大赛介绍",
            "seoKeyword": "",
            "domain": "?userId=228991",
            "pv": 0,
            "pageType": "normal",
            "sortId": 1,
            "renderId": "",
            "associateId": "fd3eb775e7d84a70b9455ec68e2f329b",
            "viewWidth": 1200,
            "synchro": false
        },
        {
            "id": 228992,
            "deleteStatus": "Normal",
            "seoTitle": "",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "大赛排行榜",
            "seoKeyword": "",
            "domain": "?userId=228992",
            "pv": 0,
            "pageType": "normal",
            "sortId": 2,
            "renderId": "",
            "associateId": "fd3eb775e7d84a70b9455ec68e2f329b",
            "viewWidth": 1200,
            "synchro": false
        },
        {
            "id": 228993,
            "deleteStatus": "Normal",
            "seoTitle": "",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "数据掘金",
            "seoKeyword": "",
            "domain": "?userId=228993",
            "pv": 0,
            "pageType": "normal",
            "sortId": 3,
            "renderId": "",
            "associateId": "fd3eb775e7d84a70b9455ec68e2f329b",
            "viewWidth": 1200,
            "synchro": false
        },
        {
            "id": 228994,
            "deleteStatus": "Normal",
            "seoTitle": "",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "大赛动态",
            "seoKeyword": "",
            "domain": "?userId=228994",
            "pv": 0,
            "pageType": "normal",
            "sortId": 4,
            "renderId": "",
            "associateId": "fd3eb775e7d84a70b9455ec68e2f329b",
            "viewWidth": 1200,
            "synchro": false
        },
        {
            "id": 241381,
            "deleteStatus": "Normal",
            "seoTitle": "",
            "seoDescn": "",
            "siteId": 69792,
            "userId": 167569,
            "name": "我的账户",
            "seoKeyword": "",
            "domain": "?userId=241381",
            "pv": 0,
            "data": "",
            "pageType": "normal",
            "sortId": 5,
            "renderId": "",
            "associateId": "07d5edb9c36f422f8d19900c50f57962",
            "viewWidth": 1200,
            "synchro": false
        }
    ];

    public static pages = [{
        "id": 10342,
        "createDate": "2016-03-05 16:08:30",
        "updateDate": "2016-03-05 16:08:30",
        "orderId": 20,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "首页",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10344,
        "createDate": "2016-03-05 16:09:09",
        "updateDate": "2016-03-05 16:09:09",
        "orderId": 19,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "产品介绍",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10345,
        "createDate": "2016-03-05 16:09:32",
        "updateDate": "2016-03-05 16:09:32",
        "orderId": 17,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "团队介绍",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10354,
        "createDate": "2016-03-05 17:20:44",
        "updateDate": "2016-03-05 17:20:44",
        "orderId": 16,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "图册",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10346,
        "createDate": "2016-03-05 16:09:42",
        "updateDate": "2016-03-05 16:09:42",
        "orderId": 15,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "服务介绍",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10343,
        "createDate": "2016-03-05 16:08:48",
        "updateDate": "2016-03-05 16:38:00",
        "orderId": 14,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "关于我们",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10657,
        "createDate": "2016-03-29 13:55:27",
        "updateDate": "2016-05-05 17:21:34",
        "orderId": 7,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "在线留言",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10683,
        "createDate": "2016-03-29 18:27:34",
        "updateDate": "2016-03-29 18:28:03",
        "orderId": 5,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "产品定价",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10356,
        "createDate": "2016-03-05 17:28:23",
        "updateDate": "2016-03-29 18:28:16",
        "orderId": 4,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "新闻动态",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10347,
        "createDate": "2016-03-05 16:10:09",
        "updateDate": "2016-03-29 18:28:12",
        "orderId": 3,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "联系我们",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }, {
        "id": 10448,
        "createDate": "2016-03-15 14:24:51",
        "updateDate": "2016-03-29 13:55:31",
        "orderId": 0,
        "deleteStatus": "Normal",
        "type": "PAGE",
        "value": "空白页面",
        "typeSon": 0,
        "showStatus": 1,
        "sectionType": "pagePC",
        "listNews": [],
        "key": "com.wqdian.common.entity.tag.Tag-0"
    }];
}